version: 2
jobs:
  build:
    environment:
      NODE_ENV: test
      NPM_CONFIG_LOGLEVEL: info
      NODE_VERSION: 4.2.6
      MOCHA_FILE: /tmp/test-results/results.xml
      multi: 'spec=- mocha-junit-reporter=-'
    steps:
      - run: |
          npm install -g npm@latest
      - run: npm install
      - run: |
          mkdir -p $( dirname $MOCHA_FILE )
          ERROR=0
          STDOUT_FILE=$( dirname $MOCHA_FILE )/stdout.txt
          STDERR_FILE=$( dirname $MOCHA_FILE )/stderr.txt
          touch $STDOUT_FILE || rm $STDOUT_FILE || touch $STDOUT_FILE
          touch $STDERR_FILE || rm $STDERR_FILE || touch $STDERR_FILE
          tail -f $STDOUT_FILE &
          tail -f $STDERR_FILE &
          npm run test -- -R mocha-multi 2> $STDERR_FILE > $STDOUT_FILE
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results